import datetime
import sys
import re
import json
from funcoesmysql import *
from funcoesjcl   import *


def main():
    # body = sys.argv[1]
    # data = json.loads(body)
    
# JCL definido como string
    jcl = '''
//JOB1 JOB (ACCT),'MR. EXAMPLE',CLASS=A,MSGCLASS=A,MSGLEVEL=(1,1)
//STEP01 EXEC PGM=PROG1
//DD01 DD DSN=DSN.PROG1.DATA,DISP=SHR
//DD02 DD DSN=DSN.PROG1.BACKUP,DISP=OLD
//STEP02 EXEC PGM=PROG2
//DD01 DD DSN=DSN.PROG2.DATA,DISP=NEW
//STEP02 EXEC CTRMLAN
//DD01 DD DSN=DSN.PROG2.DATA,DISP=NEW
//STEP03 EXEC PGM=PROG3
//DD01 DD DSN=DSN.PROG3.DATA,DISP=MOD
//STEP04 EXEC PGM=PROG4
//DD01 DD DSN=DSN.PROG4.DATA,DISP=DEL
//STEP05 EXEC PGM=PROG5
//DD01 DD DSN=DSN.PROG5.DATA,DISP=SHR
//STEP06 EXEC PGM=PROG6
//DD01 DD DSN=DSN.PROG6.DATA,DISP=OLD
//STEP07 EXEC PGM=PROG7
//DD01 DD DSN=DSN.PROG7.DATA,DISP=NEW
//STEP08 EXEC PGM=PROG8
//DD01 DD DSN=DSN.PROG8.DATA,DISP=MOD
//STEP09 EXEC PGM=PROG9
//DD01 DD DSN=DSN.PROG9.DATA,DISP=DEL
//STEP10 EXEC PGM=PROG10
//DD01 DD DSN=DSN.PROG10.DATA,DISP=SHR
//INCLUDE MEMBER=INCL1
//INCLUDE MEMBER=INCL2
'''

    leitor_jcl = ProcessJCL(jcl)
    resultado = leitor_jcl.get_info_job()
    print(resultado)

    print(json.dumps(resultado))

main()
